[tool.mypy]
python_version = "3.9"
warn_return_any = true
warn_unused_configs = true
disallow_untyped_defs = true
disallow_any_unimported = false
no_implicit_optional = true
warn_redundant_casts = true
warn_unused_ignores = true
warn_no_return = true
check_untyped_defs = true
strict_equality = true
exclude = ["src/browser_legacy/"]

# Ignore external libraries without type stubs
[[tool.mypy.overrides]]
module = ["playwright.*", "pandas.*"]
ignore_missing_imports = true

